#pragma once

#define WIN_BASE_LAYER 0
#define MAC_BASE_LAYER 4
#define DYNAMIC_KEYMAP_LAYER_COUNT 6
#define KEYCOMBO_OS_TOGGLE_ENABLE
#define KEYCOMBO_OS_TOGGLE_INDICATION_ENABLE
#define KEYCOMBO_OS_TOGGLE_HOLD_TIME 3000

#define MIDI_ADVANCED

#define TAPPING_TERM_PER_KEY

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define CAPS_WORD_INVERT_ON_SHIFT

#define LEADER_PER_KEY_TIMING
#define LEADER_TIMEOUT 250

// #define RGBLIGHT_DEFAULT_HUE
// #define RGBLIGHT_DEFAULT_SAT
// #define RGBLIGHT_DEFAULT_VAL  // brightness

#define RGB_MATRIX_TYPING_HEATMAP_DECREASE_DELAY_MS 200
