#pragma once

#define DYNAMIC_KEYMAP_LAYER_COUNT 6

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define CAPS_WORD_INVERT_ON_SHIFT

#define LEADER_PER_KEY_TIMING
#define LEADER_TIMEOUT 250

#define RGB_MATRIX_TYPING_HEATMAP_DECREASE_DELAY_MS 200
